aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:http://localhost:4566}
aws.s3.endpoint=${AWS_S3_ENDPOINT:http://localhost:4566}
aws.ses.endpoint=${AWS_SES_ENDPOINT:http://localhost:4566}
aws.sqs.endpoint=${AWS_SQS_ENDPOINT:http://localhost:4566}
aws.eventbridge.endpoint=${AWS_EVENTBRIDGE_ENDPOINT:http://localhost:4566}
aws.ssm.endpoint=${AWS_SSM_ENDPOINT:http://localhost:4566}
aws.secretsmanager.endpoint=${AWS_SECRETS_MANAGER_ENDPOINT:http://localhost:4566}
aws.cognito.endpoint=${AWS_COGNITO_ENDPOINT:http://localhost:4566}
aws.cognito.issuer-base-url=${AWS_COGNITO_ISSUER_BASE_URL:http://localhost:4566}
